### ISSUE TITLE
Cannot find any command to move, rotate, copy and mirror elements

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#314]
I could not find any basic commands to move / rotate / copy elements.

![image](https://user-images.githubusercontent.com/4086522/89808655-60f8fe80-db32-11ea-9e96-4c945678e306.png)

Could you please add some functionality to represent the following Revit Api methods?

Move:
https://www.revitapidocs.com/2015/aaddd413-01b0-2878-3f79-a281abb6d364.htm
Rotate:
https://www.revitapidocs.com/2015/3968f4e8-759c-f975-6c1f-7de42be633ed.htm
Copy:
https://www.revitapidocs.com/2015/b22df8f6-3fa3-e177-ffa5-ba6c639fb3dc.htm
Mirror:
https://www.revitapidocs.com/2015/36027166-d494-9937-74c2-d61197af3878.htm

Many thanks

**Comment by kike-garbo** [comment]
You can move elements using the 'Element Location' component.
It allows you to extract the current Location where the element is placed and allows you as well to set the desired new Location.

~~Copy elements is still missing.~~
Copy elements may be done using 'Duplicate Element'.

Mirror elements is still missing.

**Comment by kike-garbo** [comment]
Mirroring an element is weird because it changes the element every time is evaluated.

I think we need more information from the user, maybe he just enumerated all Revit transformation operations, but there is no specific need about mirror.
I'm wondering if the user can do what he wants just beeing able to Flip the element.

![image](https://user-images.githubusercontent.com/3530512/129054680-42615488-f72e-43dc-a8d0-dd365212a62a.png)
