### ISSUE TITLE
Ability to Set the LineStyle of an existing filled region.

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#932]
User is looking to modify existing Filled Regions LineStyle.  This is available as a method to change the entire Elements linestyle. 

Scripted solutions provided.
https://discourse.mcneel.com/t/change-filled-region-detail-lines-linestyle/161101/4?u=japhy

**Comment by kike-garbo** [comment]
Since 1.15 we have 'Sketch Lines' component to give access to model lines a workflow like this is now possible.
It also opens the possibility to assign different styles per edge.

![image](https://github.com/mcneel/rhino.inside-revit/assets/3530512/fa967966-b4e3-4325-bc90-d56852dbf05b)

[RiR-RegionLineStyles.zip](https://github.com/mcneel/rhino.inside-revit/files/11688314/RiR-RegionLineStyles.zip)
